version: "3.1"

services:
        pingfederate:
                image: pingidentity/pingfederate:9.3.3
                container_name: pingfederate
                command: entrypoint.sh start-server
                environment:
                        - PING_IDENTITY_ACCEPT_EULA=YES
                env_file:
                        - /home/dkgeneve/.pingidentity/devops
                ports:
                        - 9031:9031
                        - 9999:9999
                networks:
                        - pingnet
networks:
       pingnet:
