version: "3.1"

services:
  pingfederate:
    image: pingidentity/pingfederate:latest
    container_name: pingfederate
    command: entrypoint.sh start-server
    environment:
      - PING_IDENTITY_ACCEPT_EULA=YES
    env_file:
      - /home/dkgeneve/.pingidentity/devops
    volumes:
        - /tmp/pingfederate.lic:/opt/in/instance/server/default/conf/pingfederate.lic
    ports:
      - 9031:9031
      - 9999:9999
    networks:
      - pingnet
  pingaccess:
    image: pingidentity/pingaccess:latest
    container_name: pingaccess
    command: entrypoint.sh start-server
    environment:
      - PING_IDENTITY_ACCEPT_EULA=YES
    env_file:
      - /home/dkgeneve/.pingidentity/devops
    volumes:
        - /tmp/pingaccess.lic:/opt/in/instance/server/default/conf/pingaccess.lic
    ports:
      - 3000:3000
      - 9000:9000
  pingdirectory:
    image: pingidentity/pingdirectory:latest
    container_name: pingdirectory
    environment:
      - PING_IDENTITY_ACCEPT_EULA=YES
    env_file:
      - /home/dkgeneve/.pingidentity/devops
    volumes:
        - /tmp/pingdirectory.lic:/opt/in/instance/server/default/conf/pingdirectory.lic
    ports:
      - 636:636
      - 389:389
      - 8443:8443
networks:
      pingnet:
