version: "3.5"
#####################################################################
# This yaml file will start a single container of PingFederate 9.3.3
#####################################################################
services:
  pingfederate:
    image: pingidentity/pingfederate:9.3.3-edge
    container_name: pingfederate933
    command: entrypoint.sh start-server
    environment:
            #- SERVER_PROFILE_URL=https://github.com/dgeneve/PingProfiles.git
            #- SERVER_PROFILE_PATH=serverProfiles/pingfederate
      - SERVER_PROFILE_UPDATE=false
      - OPERATIONAL_MODE=STANDALONE
      - CLUSTER_BIND_ADDRESS=LINK_LOCAL
      - PF_CLUSTER_NAME=COMPOSE_PF_CLUSTER
      - DNS_QUERY_LOCATION=pingfederate-admin
      - DNS_RECORD_TYPE=A
      - PF_LOG_LEVEL=DEBUG
      - PING_IDENTITY_ACCEPT_EULA=YES
    env_file:
      - ~/.pingidentity/devops
        #volumes:
        #- /tmp/pingfederate.lic:/opt/in/instance/server/default/conf/pingfederate.lic
    ports:
      - 9031:9031
      - 9999:9999
    networks:
      - pingnet

networks:
      pingnet:
        name: pingnet
